import fs from 'node:fs';
import crypto from 'node:crypto';
import {createClient} from 'genlayer-js';
import {studionet} from 'genlayer-js/chains';
import {TransactionHashVariant} from 'genlayer-js/types';
const c=createClient({chain:studionet}),d=JSON.parse(fs.readFileSync('public/deployment.json','utf8'));
const summarize=r=>({hash:r.hash,status:r.statusName??r.status,result:r.result_name??r.resultName,execution_mode:r.execution_mode,leader_only:r.leader_only,from:r.from_address,to:r.to_address,value_wei:r.value==null?null:String(r.value),created_at:r.created_at,value_credited:r.value_credited,validator_votes:r.last_round?.validator_votes_name,leader_results:r.consensus_data?.leader_receipt?.map(x=>({execution_result:x.execution_result,result_status:x.result?.status,result_payload:x.result?.payload})),triggered_transactions:r.triggered_transactions});
const transactions=[];for(const tx of d.transactions)transactions.push({action:tx.action,...summarize(await c.getTransaction({hash:tx.hash}))});
const payout=[];for(const tx of transactions.filter(t=>t.action==='settle'))for(const hash of tx.triggered_transactions??[])payout.push(summarize(await c.getTransaction({hash})));
const read=async name=>JSON.parse(await c.readContract({address:d.contract,functionName:name,args:[0],transactionHashVariant:TransactionHashVariant.LATEST_FINAL}));
const bounty=await read('get_bounty'),evidence=await read('get_evidence');
const currentPage=await fetch(bounty.repair_url).then(r=>r.text());
const record={recorded_at:new Date().toISOString(),release:'v3',network:'Studionet',chain_id:61999,contract:d.contract,studio_account:d.studio_account,fixer:d.fixer,adversarial_attacker:d.adversarial_attacker,source_sha256:crypto.createHash('sha256').update(fs.readFileSync('contracts/access_patch.py')).digest('hex'),synthetic_evidence:true,sponsor_and_fixer_same_studio_account:false,tests:{offline_contract_behavior_tests:31,commitment_encoding_tests:1,production_build:'passed'},transactions,payout_transactions:payout,finalized_bounty:bounty,reviewed_evidence:evidence,sponsor_mutation:{url:bounty.repair_url,current_text:currentPage,current_sha256:crypto.createHash('sha256').update(currentPage).digest('hex'),approved_sha256:bounty.candidate?.page_hash,github_commits:d.fixture_mutation_commits},contract_balance_wei:String(await c.getBalance({address:d.contract}))};
fs.writeFileSync('docs/live-test.json',JSON.stringify(record,null,2)+'\n');console.log(JSON.stringify({contract:d.contract,status:bounty.status,transactions:transactions.map(t=>({action:t.action,status:t.status})),payout_transactions:payout,contract_balance_wei:record.contract_balance_wei},null,2));
