import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createClient} from 'genlayer-js';
import {studionet} from 'genlayer-js/chains';
import {TransactionHashVariant} from 'genlayer-js/types';
const client=createClient({chain:studionet});
const deployment=JSON.parse(fs.readFileSync('public/deployment.json','utf8'));
assert.equal(await client.getChainId(),61999);
assert.equal(await client.getContractCode(deployment.contract),fs.readFileSync('contracts/access_patch.py','utf8'));
const schema=await client.getContractSchema(deployment.contract);
assert.equal(schema.methods.create_bounty.payable,true);
const bounty=JSON.parse(await client.readContract({address:deployment.contract,functionName:'get_bounty',args:[0],transactionHashVariant:TransactionHashVariant.LATEST_FINAL}));
assert.equal(bounty.reward_wei,'1000000000000000000');
assert.equal(bounty.status,'PAID');
assert.equal(bounty.history[0].verdict,'RESOLVED');
assert.equal(bounty.payment.amount_wei,bounty.reward_wei);
const settlement=await client.getTransaction({hash:deployment.transactions.find(t=>t.action==='settle').hash});
assert.equal(settlement.statusName,'FINALIZED');
const payout=await client.getTransaction({hash:settlement.triggered_transactions[0]});
assert.equal(payout.statusName,'FINALIZED');
assert.equal(payout.value_credited,true);
assert.equal(String(payout.value),bounty.reward_wei);
assert.equal(payout.to_address.toLowerCase(),bounty.payment.recipient.toLowerCase());
const balance=await client.getBalance({address:deployment.contract});
assert.equal(balance,0n);
console.log(JSON.stringify({verified:true,contract:deployment.contract,sourceMatches:true,bounty,status:bounty.status,contract_balance_wei:String(balance)},null,2));
