import fs from 'node:fs';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {createClient} from 'genlayer-js';
import {studionet} from 'genlayer-js/chains';
import {TransactionHashVariant} from 'genlayer-js/types';
const c=createClient({chain:studionet});
const d=JSON.parse(fs.readFileSync('public/deployment.json','utf8'));
assert.equal(await c.getChainId(),61999);
assert.equal(await c.getContractCode(d.contract),fs.readFileSync('contracts/access_patch.py','utf8'));
const schema=await c.getContractSchema(d.contract);
for(const name of ['commit_repair','submit_repair','reopen_bounty','get_evidence','settle'])assert.ok(schema.methods[name]);
assert.equal(schema.methods.create_bounty.payable,true);
const txs=[];
for(const tx of d.transactions){
 const r=await c.getTransaction({hash:tx.hash});txs.push({action:tx.action,receipt:r});
 assert.equal(r.statusName,'FINALIZED',tx.action);
 assert.equal(r.consensus_data?.leader_receipt?.[0]?.execution_result,tx.expected_execution??'SUCCESS',tx.action);
 assert.equal(r.leader_only,false,tx.action);
}
const b=JSON.parse(await c.readContract({address:d.contract,functionName:'get_bounty',args:[0],transactionHashVariant:TransactionHashVariant.LATEST_FINAL}));
const evidence=JSON.parse(await c.readContract({address:d.contract,functionName:'get_evidence',args:[0],transactionHashVariant:TransactionHashVariant.LATEST_FINAL}));
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
assert.equal(b.status,'PAID');assert.equal(b.reward_wei,'1000000000000000000');
assert.equal(b.payment.recipient.toLowerCase(),d.fixer.toLowerCase());assert.notEqual(b.payment.recipient.toLowerCase(),d.adversarial_attacker.toLowerCase());
assert.equal(b.payment.amount_wei,b.reward_wei);
assert.equal(hash(evidence.page),b.candidate.page_hash);assert.equal(hash(evidence.report),b.candidate.report_hash);assert.equal(hash(evidence.baseline),b.baseline_hash);
assert.ok(b.history.some(h=>h.action==='SUBMIT_REJECTED'&&h.verdict==='INVALID_EVIDENCE'));
assert.ok(b.history.some(h=>h.action==='SUBMIT'&&h.verdict==='INCONCLUSIVE'));
assert.ok(b.history.some(h=>h.action==='REOPEN'));
assert.ok(b.history.some(h=>h.action==='SUBMIT'&&h.verdict==='RESOLVED'));
const livePage=await fetch(b.repair_url).then(r=>r.text());assert.notEqual(hash(livePage),b.candidate.page_hash,'Sponsor mutation must be present for this live proof');
const settle=txs.find(t=>t.action==='settle').receipt;
const payout=await c.getTransaction({hash:settle.triggered_transactions[0]});
assert.equal(payout.statusName,'FINALIZED');assert.equal(payout.value_credited,true);assert.equal(String(payout.value),b.reward_wei);assert.equal(payout.to_address.toLowerCase(),d.fixer.toLowerCase());
assert.equal(await c.getBalance({address:d.contract}),0n);
console.log(JSON.stringify({verified:true,contract:d.contract,sourceMatches:true,invalidEvidenceCannotReserveSlot:true,unresolvedCandidateReopened:true,sponsorMutationCannotVetoReward:true,payoutCredited:true,status:b.status,contract_balance_wei:'0'},null,2));
